<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '防暑套装',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '防暑套装',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '防晒护肤',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '3',
    'name' => '防晒护肤',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '日化套装',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 1,
    'id' => '2',
    'name' => '日化套装',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '日化单品',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
    'level' => 1,
    'id' => '4',
    'name' => '日化单品',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '生活家居',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '41',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => '生活家居',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '收纳箱包',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '收纳箱包',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '餐具套装',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '59',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '14',
    'name' => '餐具套装',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '42',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '食品',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '防暑食品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '6',
    'name' => '防暑食品',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '橄榄油',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '13',
    'name' => '橄榄油',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '菌菇干货',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '29',
    'name' => '菌菇干货',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '坚果礼盒',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 1,
    'id' => '7',
    'name' => '坚果礼盒',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '杂粮谷物',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '101',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 1,
    'id' => '28',
    'name' => '杂粮谷物',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '学习文具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '43',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '学习文具',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '书包',
    'measure_unit' => '1',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '25',
    'name' => '书包',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '文具套装',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '文具套装',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '笔',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '笔',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '纺织用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '43',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '10',
    'name' => '纺织用品',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '枕头',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '枕头',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '毛巾',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '19',
    'name' => '毛巾',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '床上四件套',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '16',
    'name' => '床上四件套',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '被子',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '17',
    'name' => '被子',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '家用电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '44',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '9',
    'name' => '家用电器',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '生活家电',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '21',
    'name' => '生活家电',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '厨房家电',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '20',
    'name' => '厨房家电',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '户外运动',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '11',
    'name' => '户外运动',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '健身套装',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '24',
    'name' => '健身套装',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '帐篷',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '22',
    'name' => '帐篷',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '运动背包',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '23',
    'name' => '运动背包',
  ),
);
?>